DROP TABLE IF EXISTS licoes; 

CREATE TABLE licoes (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	data_cricao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    icone INTEGER NOT NULL DEFAULT 1,
    data_previsao VARCHAR NOT NULL DEFAULT 'Indeterminado',
    titulo VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL DEFAULT '',
    prioridade INTEGER NOT NULL DEFAULT 1
);

DROP TABLE IF EXISTS tarefas; 
CREATE TABLE tarefas (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    id_licao INTEGER NOT NULL,
    data_cricao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    titulo VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) DEFAULT '',
    prioridade INTEGER NOT NULL DEFAULT 1,
    status INTEGER NOT NULL DEFAULT 0

)